### ISSUE TITLE
flag for static linking?

### ISSUE THREAD

**Issue by balenamiaa** [greenfork/nimraylib_now#13]
Would it make sense to have a compile flag for linking with a specified static library instead of a shared library? I tried 
```
dynlibOverride:raylib
passL %= "~/git_clones/raylib/src/libraylib.a"
```
but that didn't seem to help. My aim is to link with raylib compiled for the web using emscripten.

**Comment by greenfork** [comment]
> Would it make sense to have a compile flag for linking with a specified static library instead of a shared library?

My understanding is that you will have to manually compile raylib source together with your nim program. From this [wiki article](https://github.com/raysan5/raylib/wiki/Working-for-Web-(HTML5)#building-with-clioncmakeemscripten-for-web) it requires some CMake options.

All the linking is done [here](https://github.com/greenfork/nimraylib_now/blob/master/src/nimraylib_now/raylib.nim#L9-L16), so you could probably just try different options in that nim file. I am very unsure how to make it work properly with static linking and emscripten too, as far as I know you would also need some nim magic. So far just static linking seemed to work with the exception that I still had dependency on libc, but I don't remember exact steps. Probably directly editing the file is the best option for now.

**Comment by balenamiaa** [comment]
I built a static library of raylib compiled for the web following the guide on raylib's repo, then changed `{.passL:"-lraylib".}` to `{.passL:"/path/to/staticlibrary".}`, and did a few changes to the window main loop for emscripten. It worked with no problem.

What I meant was if it's possible to somehow ignore the `{.passL:"-lraylib".}` without modifying nimraylib_now, and instead link on my own?

Dependency on libc isn't a problem as the emscripten compiler handles that(, and glfw which raylib uses under the hood), but it doesn't handle arbitrary libraries like raylib.

**Comment by greenfork** [comment]
> What I meant was if it's possible to somehow ignore the `{.passL:"-lraylib".}` without modifying nimraylib_now, and instead link on my own?

I'm not sure it is possible. `--dynlibOverride` will not work because raylib and other libraries are not loaded dynamically with `dynlib`, but statically with `header`, you can see pragmas [here](https://github.com/greenfork/nimraylib_now/blob/master/src/nimraylib_now/raylib.nim#L108) (and to avoid ambiguities, it is separate from dynamic/static linking, those 2 options exist for dynamic linking). And I don't know if there's an option to override all past `passL` options for gcc llvm or whatever linker is used.

Do I understand correctly that the only thing you did was "changed {.passL:"-lraylib".} to {.passL:"/path/to/staticlibrary".}" inside this library and then "did a few changes to the window main loop" inside your game code? If so, we can introduce a custom flag to override all the `passL` things.

**Comment by balenamiaa** [comment]
I tried it from fresh and yes that's all that was needed: https://github.com/balenamiaa/nimraylib_now_wasm.git is a working example. I compiled it with the following in my case: `nim c -d:wasm="/home/tbalen/git_clones/raylib/src/libraylib.a" raylib_wasm.nim`

**Comment by greenfork** [comment]
@balenamiaa I added emscripten support. Could you check out [this example](https://github.com/greenfork/nimraylib_now/tree/master/examples/emscripten) and see if it works for you?

Also pushed new tag and release https://github.com/greenfork/nimraylib_now/releases/tag/v0.10.0

**Comment by balenamiaa** [comment]
No, it's alright :). The example for emscripten works for me just fine, good job!
