### ISSUE TITLE
Allow support for image formats that are off by default?

### ISSUE THREAD

**Issue by Skaruts** [greenfork/nimraylib_now#41]
Hi, is there some way to turn on support for images that are turned off by default? (.JPG, TGA, etc)

I looked at the code and I didn't see any `when defined` statements related to this, so I'm guessing there isn't. But I'm wondering if there's some workaround for it. 

(in the original code this is done with [compile time flags](https://github-wiki-see.page/m/raysan5/raylib/wiki/CMake-Build-Options), e.g. `SUPPORT_FILEFORMAT_JPG`.)

**Comment by greenfork** [comment]
It should be possible by just supplying the flags somewhere in the build script https://github.com/greenfork/nimraylib_now/blob/master/src/raylib_build_static_template.nim, I can take a look. Which exact flags are you interested in?

**Comment by Skaruts** [comment]
Specifically these
```
  SUPPORT_FILEFORMAT_BMP	
  SUPPORT_FILEFORMAT_TGA	
  SUPPORT_FILEFORMAT_JPG	
  SUPPORT_FILEFORMAT_GIF	
  SUPPORT_FILEFORMAT_PSD	
```

**Comment by greenfork** [comment]
@Skaruts I think it makes sense that you would want to customize the build flags for your own use case. As I understand, this is mainly to reduce the overall size of the library. Here you can see the default flags (in this NimraylibNow! library and in downloadable library from official repo CMake isn't used, only make, the CMake file is an external contribution):
https://github.com/raysan5/raylib/blob/93168304cd377fabec9dfa88469f2cc635cd6326/src/config.h#L133-L145

So in order to activate these flags in your own build, you can put this code into your main file:
```nim
{.passC:"-DSUPPORT_FILEFORMAT_BMP".}
```

or you can supply these flags to nim compiler as in this issue https://github.com/greenfork/nimraylib_now/issues/37:
```
nim c --passC:"-DSUPPORT_FILEFORMAT_BMP" --gc:orc file.nim
```

or you can put these files into your `nim.cfg` or `config.nims` in the root directory:
```nim
--passC:"-DSUPPORT_FILEFORMAT_BMP"
```

I believe we should go with this approach since Raylib decided to go this way too. Please let me know if there are any issues with that or you have any thoughts on this topic.

**Comment by Skaruts** [comment]
Nice! That works just fine, and it seems it's all I really need.

Thank you.

**Comment by greenfork** [comment]
Glad to hear, goodluck with your project!
