### ISSUE TITLE
drawRay doesn't work

### ISSUE THREAD

**Issue by Psirus** [greenfork/nimraylib_now#7]
When I run the `core_3d_picking` example, the ray doesn't get drawn. I tried the original C example; there it works. There are no warning messages, it compiles and runs nicely otherwise. I'm on Ubuntu 20.04, with the raylib 3.5.0. Let me know if you need more information.

Thank you for this wrapper, btw!

**Comment by Intasx** [comment]
I think this should fix it:
https://github.com/greenfork/nimraylib_now/blob/5bf3ec43d9d82f63ddfec88aebe9d365a2371360/examples/core/core_3d_picking.nim#L49
That `let` is not supposed to be there, because it would create a new ray limited to the scope of the `if` instead of using the one declared here:
https://github.com/greenfork/nimraylib_now/blob/5bf3ec43d9d82f63ddfec88aebe9d365a2371360/examples/core/core_3d_picking.nim#L31-L35
After removing that `let` the ray is drawn correctly.

**Comment by Psirus** [comment]
I didn't even think it could be this easy. Thanks.

**Comment by greenfork** [comment]
Thank you for reporting, it is fixed on master!
