### ISSUE TITLE
How can I use the Raygui textInputBox?

### ISSUE THREAD

**Issue by arnaudchenyensu** [greenfork/nimraylib_now#74]
Hi,

I'm new to Nim (and Raylib). I'm trying to use the `textInputBox` from Raygui but without much success:

```nim
import nimraylib_now

const screenWidth = 800
const screenHeight = 450

initWindow(
  screenWidth,
  screenHeight,
  "raylib [text] example - input box"
)

# if text is empty, the program will crash on input
var text = ""

while not windowShouldClose():
  # Update
  if isKeyDown(KeyboardKey.LEFT_SUPER) and
    isKeyDown(KeyboardKey.BACKSPACE):
    # if I reset to an empty string, the program will crash too
    text = ""

  # Draw
  beginDrawing():
    clearBackground(White)

    discard textInputBox(
      Rectangle(x: 0, y: 0, width: 200, height: 200),
      "text input box",
      "my input",
      "buttons",
      text
    )

#  De-Initialization
closeWindow()
```

How should I use `cstring` on `textInputBox`?

Thanks in advance for helping,
Arnaud.

**Comment by greenfork** [comment]
Hey, Arnaud! Thanks for a detailed reproducible example, it really helps!

I think the problem is buffer overflow. Doing

```nim
var text = ""
```

won't necessarily allocate as many bytes as you want.

I managed to solve it with [`newString`](https://nim-lang.org/docs/system.html#newString%2CNatural):

```nim
var text = newString(10).cstring
```

the idea is that you pass `text` as a reference to the `textInputBox` and `text` already has a necessary amount of memory already allocated. I checked that it works with the following snippet:

```nim
  if isKeyDown(KeyboardKey.A):
    echo text
```

Let me know if you have troubles still.

**Comment by arnaudchenyensu** [comment]
Thank you, it's exactly what I needed. Do you know how much memory does it allocate? Or how many characters that can be typed with `newString(1).cstring`?

**Comment by greenfork** [comment]
The number is the number of bytes. If you use English language only, then 1 character is 1 byte. If you use other languages, you can use [this tool](https://www.javainuse.com/bytesize) I've just found by googling "how many bytes in string online".

**Comment by arnaudchenyensu** [comment]
Thank you, but when I'm using `newString(1).cstring` I can type more than one character.

Is it because strings seem to be implemented as [sequences in Nim](https://nim-lang.org/docs/manual.html#types-array-and-sequence-types)?

**Comment by greenfork** [comment]
When you do "buffer overflow", all extra bytes are written into random memory. If this so happens, that this random memory is your currently executing program - you get "illegal exception error". If this doesn't happen, you will continue as normal, but occasionally your game will crash because of this error. This is a hard to track error.

**Comment by arnaudchenyensu** [comment]
Thank you for the information!
