### ISSUE TITLE
Window showing up on wrong monitor with linux (kubuntu 22.04.1)

### ISSUE THREAD

**Issue by pyryrin** [greenfork/nimraylib_now#85]
Window showing up on wrong monitor with linux (kubuntu 22.04.1). I tried setWindowMonitor(getCurrentMonitor()) but it just made the window fullscreen on the wrong monitor.

**Comment by greenfork** [comment]
Thanks for telling about this bug! It is fixed on Raylib master https://github.com/raysan5/raylib/issues/2728. This will be fixed in NimraylibNow! once Raylib releases the next version and I will subsequently upgrade to it. So far a workaround is to make your "desired" monitor the "first one". For example, on my laptop + external monitor I run this command to make my laptop's monitor "first":

```
xrandr --output HDMI-1 --right-of eDP-1 --auto
```

where HDMI-1 is my external monitor and eDP-1 is my laptop's monitor. You can run just `xrandr` to get information on how your monitors are called.

This is only a problem for Xorg, on Wayland using river composer I don't such a problem.

I will close this issue for now, if it happens again after the upgrade to the next Raylib version, feel free to re-open it, thanks!
